### ISSUE TITLE
Data about the Oncology Screen dataset and the DrugCombDB dataset

### ISSUE THREAD

**Issue by Royluoyi123** [GSanShui/SynergyX#1]
Dear author:
Can you provide the data about the Oncology Screen dataset and the DrugCombDB dataset that you used in this project?

**Comment by GSanShui** [comment]
Thanks for your inquiry. The independent datasets utilized in this project have been provided under the directory `SynergyX/data/independent dataset`.  Please locate the `**_all_items.py` file for access and use the `train_test_split` function from the `sklearn` package for dataset partitioning.

**Comment by hellomonsterr** [comment]
Hello author, the data in Table 1 of the paper is not the same as the values stated in the Synergy dataset, do you have the original data, and the data in the independent dataset under the data in the code is also different from the values in Table1, has it been processed in other ways?
