### ISSUE TITLE
A version mistake in synergyX's file

### ISSUE THREAD

**Issue by Yeaee** [GSanShui/SynergyX#6]
When  using   --celldataset 3 , the file name in 963g can't match.

985_cellGraphs_exp_mut_cn_963_genes_norm.npy should be the right file , instead of 985_cellGraphs_exp_mut_cn_963_genes.npy.

However，the version supported in https://zenodo.org/records/8289295, as Guo mentioned in BIB is not the right version yet.

Simply changing file name isn't working.

**Comment by GSanShui** [comment]
Sorry for the mistake. I have released the correct version of this file in release 1.1(https://github.com/GSanShui/SynergyX/releases/tag/1.1)
