### ISSUE TITLE
preprocessing raw dataset

### ISSUE THREAD

**Issue by uxiaveleiro** [GSanShui/SynergyX#7]
Hello, thank you for your code.

I cannot find the code for preprocessing of the original drug combination data sourced from DrugComb (v1.5). The original file is named 'summary_v_1_5.csv' ([https://drugcomb.org/download/](https://drugcomb.org/download/)).

**Comment by GSanShui** [comment]
Thank you for your question. In fact, you do not need the original preprocessing code from our repository. We simply filtered the data based on the available features for cells and drugs, and applied the constraints on the S score range as described in the related paper to generate the all_items.npy file. You can perform the necessary data preprocessing according to your specific requirements.
